language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
before_script:
- npm update --dev
script:
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_f48a2cbd8a1b_key -iv $encrypted_f48a2cbd8a1b_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: emVbwX5PSTwmDQXs62907Q/LiV98dpfBWB/TrKxj0KwfDcRYeEwv7iSDILOaYZC3nm0uCKlVV5HELVkbNUTgxWCuv2pdWfFRpPur7kp4KheirneWr6SqN36ycp3VA3EIlf0cUGz8Pog2CtIez/IMHmavjAWdi+GUCKjawn5lGnypUI3qMM0ggMHtkNZTE8JAJ4P6MMxDUiNan3Y5Zaa/oHpObitGDZq4agutf9ke2G20lPc3O808NthL26F27p4XQ6tDhiHGvIvqib/EyWPcFuEC/53CFn3rWeTLALSVO8d8XwJiBIPXoli4l0kElZwi4A9ZcCNg2Ys6GifibeQ/OzSam1gBcAOy6hA/5A/p/Slt8M/iByLYNCN8/jKLPmYDVvvEwsLJ7vm5N52bFuDFYrVPOHy6o05L4HFWQEerKqrzgF2i/9HHLyNDC/ouVQFMIyD75MJgEi+cmU1FcMdCwHlc283xVpoaht4eHzmhkS5j1cU952pVnbXEgrU5g6uDyqjsrsQvwUoVpkd5xBFcgGaKeUf4tePbFU3wIpGVNRK4Jm8yhjhOSiZERKOd/0sQIAEL0WR0i+1dX3m70DXOX6NUpWTIUDaKRsXAoTJuqrsbr3aoWl7Bq6FGz2zwC+JcVlv223zIpwsAjNcWyOZ9aBLpiQT/fgmezrgcz7UiYcA=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - secure: FydsMiSl7NUdusYRQuCapVynAUrJj5fG5feKLHr4vBz32mZ+S7GBAWQc0kZl8lA7ip8NZigu4qUkUYv957YNhrMd8noi4YWelSsiX2RDkb7st4ze+bmDtwmOXVt6qGl0nHeNYyzLF8VAju2k78PzkEvHnts7J75YfTaDnOmTTRw0BUwrhhMIoBvzDh+bKARfORz9hl6oySL3pbMnegXs/aAvDf1hGb+YJzGvphKKzFg4K/lVIbeeAhVbluiSw8+Q2mVn045qhvRLKz9+ngwq1cM9IR7CO+ePDuEjvsIU2v7RYnXvefybMJuKOD2Ft9j57jXfXWdB/Df1wng7FNSPsRMQUaUGyCAE/nbr14gYI7rRvf7aFjQ7s0UHwxY+eCBt+INpxB2Po57vP6xZAx3pco+eWiTfGHP+QfX7lXxZ9VE+mOOeeCsbebDIUUzl8eAsFQzurxBP22fDnDOaVriIx0oKM7IGeD1Sqv1CyCXez53sl9z4Az52c2Yj1XXO3+5hVp1CEfOE2vvE+IlXpP5hc1c0+nhgalUQ06/DS4UdDQIRCz3zEmpurN9iFfV6nSxZan136BUwcVMAMJCx6xAdQ/PnXzdk3C+rOu0uUOofioeKPMKKCL46w2XaotzP39PoMJ+i8ou5GA9qFeHOpbPrkkCl4/FT1hcUDr2APHAJfRA=
  - secure: oFzED4QdXD3DZVtLbmreGxo0I60jOG0gMFvWFmgRm/Bw/Pp+fcyYC1LaK20LR6bnmofczVY/asJEzeWmAM+ODzMETrRWDjxyal08pPHcfOcIYZGqzPzmx2dS7v9sM2NkBEfoSD1rxYWyYfpHqyi9mWWjsCjECMEC4qPmfIAgNzEJwZn2wDXhGavXaTZtS7W8KHk+aOc6TfGgjQtyIft+FsAHk2O9gi2l0CYQosSVGpA+J/Edv/VDxhuxvn7EGvmmQoUzXq0ImeTL5OqR5kGV5/241f4ms0Jrn8hLhQxuxisr7MmKQxU+bBbFGolKfNpSz8+8HqnnU2/KgUNlnoIMBUmFRIXOPdMiV7uuN2+UFTmYU57QaSJcHi22BKvaMaHiSEn/Z3JfaSB9cH4Q3+2hxttK5ErWn4h+gsKbUmqpGv1SgV3EZFDFyHN3GZSnHtERKIVyDT3XQNDAJVLY5iRW6MhBySJ6m5yxbLEZE3gS/Se6gf+SWz+mOHrW9qNjBjlf5vDg+T6ZGVntp6jArgWgc70XEf6f3fjg0i3u105MKfWeM0U+Qm3axDsRm0JyvEdw30J1I75OR/h3C1taDhlkC9R5XOAyEH/vX6sSSATm0q/F7fkHoaKA3RpewMF0vfRzkhyngdxyNqhiFYb5ABPPtdZKocat9BlwT/RY996LHd8=
  - secure: SThhX7W7Z8o6EvYBcd9gtBduB3xe8A9QU5kqypnu1yfACtJ23CKsxyel4iIhnkWqVC/B/G8x8uzvbisFTx2+n8ycn/14hzv6PYs9gYoWKUXg51lBnDGOCbXQ4UKXp6mxxLi2Ym4luFvHXOnUicceQeKewtOiHr3n/69lNGfvgMtbBl5gkuTF0jeD5J7jjFDkvNp2Ae2RSrWuUrnQ2/2NnmDLFjW+lOmCLOoZNiXGr12DnkgzGgIkoVy49anHKRxOejLtEXgn9hzNgan8Bz7oz88XWwF8lrXNotJ/VgPxxT7cH8EI3Fg/I6fsbeUZTL3zGZurE2eWb+d7mm0wlHkacAqJW0T/mSQipZc6imDONK/SVRXscfbcWA3jyIKqEsfTTZBqg5fopEp5R6GADEGgfhDuDo3HPMi43VdpoTfSYuhAxNxqJu8oKvijpXWoqr5WFQl+V+CAFiyyGdl/YqsG5XH50FDDrkvHeahQw/BZHr7GGw5AGYXE/1yMI9TcKLSm8ZtdqcAtyeZovajLtr8Y/4zuBB2yqQ1rNrrmFVVbcJlkw5OJ6nMK7rMvZy5rj4NeMmBJ4Fb+0sIqNvqbohNP6NnbOVM1kTyN1QA0/6q22ZfTD2OhNDSGJV+MmAJG1APohiIDXOPWgQaIsOWOJwmJ98YCH+4AcCyFy+m7nvFLM0Y=
