template:
  image: slidewiki/webrtcsignalingservice:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=signalingservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=signalingservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
  volumes:
    - /data/slidewiki-deployment/docker-compose/twitterConfig_experimental.json:/nodeApp/config.json:ro
