template:
  image: slidewiki/webrtcstunservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=stunservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=stunservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
